basePath: /
definitions:
  request.ParamLogin:
    properties:
      password:
        description: 用户密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - username
    type: object
  request.ParamSignUp:
    properties:
      password:
        description: 用户名密码
        type: string
      re_password:
        description: 确认用户密码
        type: string
      username:
        description: 用户名
        type: string
    required:
    - password
    - re_password
    - username
    type: object
host: 127.0.0.1:8888
info:
  contact: {}
  description: This is a sample Server pets
  title: web_app
  version: 0.0.1
paths:
  /api/v1/login:
    post:
      parameters:
      - description: 用户名, 密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ParamLogin'
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1000,"msg": "success","data": ""}'
          schema:
            type: string
      summary: 用户登录
      tags:
      - Base
  /api/v1/signup:
    post:
      parameters:
      - description: 用户名, 用户密码，确认密码
        in: body
        name: data
        required: true
        schema:
          $ref: '#/definitions/request.ParamSignUp'
      - description: Bearer 用户令牌
        in: header
        name: Authorization
        type: string
      produces:
      - application/json
      responses:
        "200":
          description: '{"code": 1000,"msg": "success","data": ""}'
          schema:
            type: string
      summary: 用户注册
      tags:
      - Base
securityDefinitions:
  ApiKeyAuth:
    in: header
    name: x-token
    type: apiKey
swagger: "2.0"
